name: okapi CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pull_request:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: lein deps
     - run: lein test
