name: PR check

on:
  pull_request:
    branches: [ master ]

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: lein test
    - uses: 8398a7/action-slack@v3
      if: always()
      with:
        text: "PR Title: ${{ github.event.pull_request.title }}"
        status: ${{ job.status }}
        fields: repo,commit,author,took
      env:
        GITHUB_TOKEN: ${{ github.token }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      
